[build]
  # Explicitly build from the root context
  command = "cd frontend && npm install && npm run build"
  
  # Point to the resulting build folder relative to the root
  publish = "frontend/build"

# This handles the "Page Not Found" (404) errors for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
